### ISSUE TITLE
FD issue

### ISSUE THREAD

**Issue by da-martin** [jon-heard/obsidian-text-expander-js_shortcutFileLibrary#1]
Hi Jon!
I'm coming from the Mythic GME discord server.
I'm trying your plugin and got this from the **;;fd100;** shortcut:
![image](https://user-images.githubusercontent.com/98848875/175838359-7f5bfaa0-b2d7-4006-bf85-6c7ad538a480.png)
This is in source mode, I guess this is not the intended behavior.
As you see the **;;XdX;** shortcut is not working at all for me, do you want me to open a separate Issue for that?
Thank you for making this plugin, it has lots of potential!

**Comment by da-martin** [comment]
Sorry, I just realized this is the wrong repo.

**Comment by jon-heard** [comment]
Hi.  Just noticed this.  Sorry for the delay.  I'd suggest adding to https://github.com/jon-heard/obsidian-text-expander-js/discussions going forward.

The first thing that I'd try is to run ;;ref settings;.  This expands to a list of shortcuts in the settings.  The last one should have the syntax of __{count}d{max}{add}__.  This is the shortcut that would handle ;;1d100; and ;;2d100;.  The rest of your output looks good.

So, if you see __{count}d{max}{add}__ in the list, the next thing I'd try is to remove it in the settings, then click the "Add defaults" button at the top of the shortcuts list.  If you do NOT see it in the list, then _just_ click the "Add defaults" button.

Let me know if you are still having issues after this.

**Comment by jon-heard** [comment]
Oh, whoops.  I just noted that you closed this as completed.  I hope the issue was resolved for you.

**Comment by da-martin** [comment]
Hi,
So I tried what you said (deleting the shortcut and clicking "Add defaults", but it still didn't work.
I got this in the console:

```
SHORTCUT-EXPANSION-ERROR
    Uncaught SyntaxError: Invalid or unexpected token
    line: 19, column: 38
    ────────────────────
0001 function roll(max) { return Math.trunc(Math.random() * max + 1); }
0002 let $1 = "2";
0003 let $2 = "10";
0004 let $3 = "";
0005 $1 = Number($1) || 1;
0006 let result = 0;
0007 let label = "D" + $2;
0008 if ($1 > 1) { label += "x" + $1; }
0009 for (let i = 0; i < $1; i++) { result += roll($2); }
0010 if ($3) {
0011 	if ($3.startsWith("+")) {
0012 		result += Number($3.substr(1));
0013 	} else {
0014 		result -= Number($3.substr(1));
0015 	}
0016 	label += $3;
0017 }
0018 if (isNaN(label.substr(1))) { label = "(" + label + ")"; }
------------------------------------------v
0019 return "🎲 " + result + " /" + label;"
------------------------------------------^
0020 
```

**Comment by da-martin** [comment]
Oh I just realized the console is pointing at the extra " after the semicolon. I deleted it in the shortcut and that fixed it.
Sorry, I should have caught that straight away.

**Comment by jon-heard** [comment]
No problem.  Glad that this was resolved for you.
